services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
  db:
    image: postgres
    restart: unless-stopped
    shm_size: 128mb
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-d", "db_prod" ]
      interval: 10s
      timeout: 3s
      retries: 5
    environment:
      POSTGRES_DB: mrp
      POSTGRES_USER: mrp
      POSTGRES_PASSWORD: mrp
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  adminer:
    image: adminer
    restart: always
    ports:
      - "8081:8081"

volumes:
  postgres-data: