package me.duong.mrp.repository;

import me.duong.mrp.utils.Logger;

import java.sql.*;

public class DbSession implements AutoCloseable {

    private Connection connection;

    public DbSession() {
        createConnection();
        disableAutoCommit();
    }

    public PreparedStatement prepareStatement(String sql) {
        return prepareStatement(sql, -1);
    }

    public PreparedStatement prepareStatement(String sql, int autoGeneratedKeys) {
        if (connection == null) throw new DbException("No active connection");
        try {
            if (autoGeneratedKeys != -1) {
                return connection.prepareStatement(sql, autoGeneratedKeys);
            }
            return connection.prepareStatement(sql);
        } catch (SQLException exception) {
            throw new DbException(exception.getMessage());
        }
    }

    public void commit() {
        if (connection == null) return;
        try {
            connection.commit();
        } catch (SQLException exception) {
            Logger.error("Failed to commit: %s", exception.getMessage());
        }
    }

    public void rollback() {
        if (connection == null) return;
        try {
            connection.rollback();
        } catch (SQLException exception) {
            Logger.error("Failed to rollback: %s", exception.getMessage());
        }
    }

    private void createConnection() {
        connection = DbConnection.INSTANCE.getConnection();
    }

    private void disableAutoCommit() {
        if (connection == null) return;
        try {
            connection.setAutoCommit(false);
        } catch (SQLException exception) {
            Logger.error("Auto-Commit not disabled: %s", exception.getMessage());
        }
    }

    private void dispose() {
        if (connection == null) return;
        try {
            connection.close();
            connection = null;
        } catch (SQLException exception) {
            Logger.error("Failed to close connection: %s", exception.getMessage());
        }
    }

    @Override
    public void close() {
        dispose();
    }
}
